In [1]:
import tensorflow as tf
from GAE import GAE
from spektral.layers import GCNConv
from spektral.utils import gcn_filter
import rustworkx as rx
import rustworkx.generators as rxg
import numpy as np
from rustworkx.visualization import mpl_draw

In [1]:
from GAE import GAE
import rustworkx.generators as rxg

In [2]:
graph = rxg.directed_path_graph(200)
model = GAE(100, 100)

2024-01-23 14:36:40.880478: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Max
2024-01-23 14:36:40.880504: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 32.00 GB
2024-01-23 14:36:40.880512: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 10.67 GB
2024-01-23 14:36:40.880556: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-01-23 14:36:40.880576: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
import tensorflow as tf
k = tf.ones(100)
k@tf.transpose(k)



InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:GPU:0}} In[0] and In[1] ndims must be == 2: 1 [Op:MatMul] name: 

In [7]:
print(encoding, numeric_representation)

tf.Tensor(
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(200, 200), dtype=float32) [[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
